### ISSUE TITLE
A question about the speed

### ISSUE THREAD

**Issue by fandulu** [xingyizhou/GTR#12]
Thanks for releasing this great work. May I ask for more details about the speed evaluation?

For TAO data, as you used the default detectron2, may I know if you count the inference time of detectron2 for 11.2 FPS, or only the GTR inference time? Since the TAO video sampling rate may not be 30 FPS, does it need to consider this factor and transfer the inference speed?

Thanks.

**Comment by xingyizhou** [comment]
Hi,

  The inference time **includes** the detector part in detectron2. We only use the keyframes in TAO so the original data is sampled at 1 FPS. The runtime we reported is only the inference run time, regardless of the video sample rate.

Best,
Xingyi

**Comment by fandulu** [comment]
Got it, Thanks very much for your replying.
