### ISSUE TITLE
Your test dataset overlaps with the training dataset

### ISSUE THREAD

**Issue by wshku** [xingyizhou/GTR#33]
Hi,

Your mot training dataset and test dataset, generated by convert_mot2coco.py, are overlapped.
That comparison seems unfair...

**Comment by iTruffle** [comment]
Hello, How to solve this problem?

**Comment by iTruffle** [comment]
I have solved the problem. 
trainval === test
and modify the path code in convert_mot2coco.py
![image](https://user-images.githubusercontent.com/80766557/190336306-a0edff62-54dd-4214-8dc6-9d01dc662cda.png)
