### ISSUE TITLE
can't evaluate on MOT17

### ISSUE THREAD

**Issue by noahcao** [xingyizhou/GTR#7]
Hi Xingyi,

I believe the guidelines you write at [the doc](https://github.com/xingyizhou/GTR/blob/master/docs/MODEL_ZOO.md) has some issue. To be precise, to directly evaluate on MOT17 by:
```
python train_net.py --config-file configs/GTR_MOT_FPN.yaml --eval-only MODEL.WEIGHTS  output/GTR_MOT/GTR_MOT_FPN/model_0004999.pth
```
we will get the error as:
**gtr.tracking.trackeval.utils.TrackEvalException: GT file not found for sequence: MOT17-02-FRCNN**

Besides, to evaluate on the self-splitted half-val, I assumed we need the files "gt_val_half.txt" under the directory of each sequence?

Could you help to double check if your guideline can work fine with the current version and reach the requirement of the [TrackEval ](https://github.com/JonathonLuiten/TrackEval)lib you adopted? I thought you may miss some guidelines about data splitting and preparation?

**Comment by noahcao** [comment]
I realized that was caused by failure of saving results files when converting mot to coco. I made a simple [PR](https://github.com/xingyizhou/GTR/pull/8#issue-1203765863) to fix this.

**Comment by xingyizhou** [comment]
Thank you! The PR is merged :)
